# Generated by Django 4.1 on 2023-01-27 21:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(blank=True, max_length=200, null=True)),
                ('blog_slug_title', models.SlugField(max_length=200, unique=True)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('date_published', models.DateTimeField(default=datetime.datetime(2023, 1, 27, 21, 9, 12, 718750, tzinfo=datetime.timezone.utc))),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ['-date_published'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['blog_title', 'blog_slug_title'], name='blog_post_blog_ti_f1d652_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['body'], name='blog_post_body_5222b4_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status'], name='blog_post_status_02ce19_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['date_published', 'date_created'], name='blog_post_date_pu_3cd6c3_idx'),
        ),
    ]
