# Generated by Django 4.1 on 2023-01-27 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 21, 15, 32, 612077, tzinfo=datetime.timezone.utc)),
        ),
    ]
