# Generated by Django 4.1 on 2023-01-27 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 21, 26, 37, 432724, tzinfo=datetime.timezone.utc)),
        ),
    ]
