# Generated by Django 4.1 on 2023-01-28 10:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_img',
            field=models.ImageField(default='', upload_to='blog/post/%Y%m%d', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='post',
            name='is_recent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='recent_img',
            field=models.ImageField(default='', upload_to='blog/recent/%Y%m%d', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='post',
            name='trend_img',
            field=models.ImageField(default='', upload_to='blog/trends/%Y%m%d', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 10, 18, 40, 765438, tzinfo=datetime.timezone.utc)),
        ),
    ]
