# Generated by Django 4.1 on 2023-01-28 12:00

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_blog_img_post_is_recent_post_is_trending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_img',
            field=models.ImageField(default='blog/post/default.jpg', upload_to='blog/post/%Y%m%d', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 12, 0, 49, 239330, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='recent_img',
            field=models.ImageField(default='blog/recent/default.jpg', upload_to='blog/recent/%Y%m%d', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='post',
            name='trend_img',
            field=models.ImageField(default='blog/trends/default.jpg', upload_to='blog/trends/%Y%m%d', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
