# Generated by Django 4.1 on 2023-01-28 12:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_blog_img_alter_post_date_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_img',
            field=models.ImageField(default='blog/post/20230128/default.jpg', upload_to='blog/post/%Y%m%d', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 12, 13, 20, 941072, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='recent_img',
            field=models.ImageField(default='blog/recent/20230128/default.jpg', upload_to='blog/recent/%Y%m%d', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='post',
            name='trend_img',
            field=models.ImageField(default='blog/trends/20230128/default.jpg', upload_to='blog/trends/%Y%m%d', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
