# Generated by Django 4.1 on 2023-01-28 19:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_cooment_alter_post_date_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(blank=True, default='images/recent-commnet-img.jpg', upload_to='blog/comment/%y%m%d')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Cooment',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 19, 49, 9, 47007, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_posts', to='blog.post'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['name'], name='blog_commen_name_b274f8_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['email'], name='blog_commen_email_9c3264_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['body'], name='blog_commen_body_d5e86f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created', 'active'], name='blog_commen_created_83d41c_idx'),
        ),
    ]
