# Generated by Django 4.1 on 2023-01-28 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment_delete_cooment_alter_post_date_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_img',
            field=models.ImageField(blank=True, default='blog/comment/recent-commnet-img.jpg', upload_to='blog/comment/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 19, 57, 37, 557279, tzinfo=datetime.timezone.utc)),
        ),
    ]
