# Generated by Django 4.1 on 2023-01-29 00:45

import datetime
import django.core.validators
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0015_alter_post_blog_img_alter_post_date_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_img',
            field=models.ImageField(blank=True, default='blog/comment/recent-commnet-img.jpg', upload_to='blog/comment/%Y%m%d', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 29, 0, 45, 11, 166793, tzinfo=datetime.timezone.utc)),
        ),
    ]
